# Generated by Django 5.2.17 on 2026-09-11 19:59

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registration_request_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('path', models.CharField(editable=False, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='events.orgnode')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='events.orgnode')),
            ],
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.orgnode')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guest_events', through='events.EventGuest', to='events.orgnode'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.orgnode'),
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['path'], name='events_orgn_path_50e912_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgnode',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'organization')), fields=('kind',), name='una_sola_organizacion'),
        ),
        migrations.AddConstraint(
            model_name='orgnode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('parent'), name='nombre_unico_entre_hermanos'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'node'), name='una_membresia_por_nodo'),
        ),
        migrations.AddConstraint(
            model_name='eventguest',
            constraint=models.UniqueConstraint(fields=('event', 'node'), name='invitado_unico_por_evento'),
        ),
    ]
