# Generated by Django 5.2.17 on 2026-09-11 19:59

from django.conf import settings
from django.db import migrations


def sembrar_organizacion(apps, schema_editor):
    OrgNode = apps.get_model('events', 'OrgNode')
    Membership = apps.get_model('events', 'Membership')
    Event = apps.get_model('events', 'Event')
    SiteSettings = apps.get_model('events', 'SiteSettings')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    default_name = SiteSettings.objects.filter(pk=1).values_list('organization', flat=True).first() or 'Life'
    root, created = OrgNode.objects.get_or_create(kind='organization', defaults={'name': default_name})
    if created:
        # Los modelos históricos de RunPython no pasan por OrgNode.save(): el path se calcula a mano.
        OrgNode.objects.filter(pk=root.pk).update(path='/' + str(root.id) + '/')

    Event.objects.filter(owner__isnull=True).update(owner_id=root.pk)

    con_membresia = Membership.objects.values_list('user_id', flat=True)
    for user in User.objects.filter(is_staff=True).exclude(id__in=con_membresia):
        Membership.objects.create(user=user, node=root, role='apostol')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_org_expand'),
    ]

    operations = [
        migrations.RunPython(sembrar_organizacion, migrations.RunPython.noop),
    ]
