# Generated by Django 5.2.17 on 2026-09-11 19:59

import django.db.models.deletion
from django.db import migrations, models


def rellenar_owner_faltante(apps, schema_editor):
    # Cubre eventos creados por el contenedor viejo entre 0003 y 0005 durante el despliegue.
    OrgNode = apps.get_model('events', 'OrgNode')
    Event = apps.get_model('events', 'Event')
    root = OrgNode.objects.get(kind='organization')
    Event.objects.filter(owner__isnull=True).update(owner_id=root.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_org_seed'),
    ]

    operations = [
        migrations.RunPython(rellenar_owner_faltante, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.orgnode'),
            preserve_default=False,
        ),
    ]
